Repository parallaxsecond/parsec-book, pull requests merged in 2020-04, with the labels that each got.

#22 Use UTF-8 characters in coverage page
  src/api_coverage.md
Labels: bug

#23 Update content and format of all operations
  src/SUMMARY.md
  src/parsec_client/operations/README.md
  src/parsec_client/operations/list_opcodes.md
  src/parsec_client/operations/list_providers.md
  src/parsec_client/operations/ping.md
  src/parsec_client/operations/psa_asymmetric_sign.md
  src/parsec_client/operations/psa_asymmetric_verify.md
  src/parsec_client/operations/psa_destroy_key.md
  src/parsec_client/operations/psa_export_public_key.md
  src/parsec_client/operations/psa_import_key.md
  src/parsec_client/operations/psa_key_attributes.md
  src/parsec_client/operations/psa_sign_hash.md
  src/parsec_client/operations/psa_verify_hash.md
Labels: documentation

#25 Add various updates
  src/parsec_client/operations/list_opcodes.md
  src/parsec_client/operations/psa_import_key.md
  src/parsec_client/wire_protocol.md
Labels: invalid

#26 Add Contribution Guidelines and update copyrights
  CONTRIBUTING.md
  DCO.txt
  README.md
  ci/check_format.sh
  src/README.md
  src/SUMMARY.md
  src/api_coverage.md
  src/contributing.md
  src/overview.md
  src/parsec_client/README.md
  src/parsec_client/api_overview.md
  src/parsec_client/operations/README.md
  src/parsec_client/operations/add_client.md
  src/parsec_client/operations/list_opcodes.md
  src/parsec_client/operations/list_providers.md
  src/parsec_client/operations/ping.md
  src/parsec_client/operations/prove_client.md
  src/parsec_client/operations/psa_algorithm.md
  src/parsec_client/operations/psa_destroy_key.md
  src/parsec_client/operations/psa_export_public_key.md
  src/parsec_client/operations/psa_generate_key.md
  src/parsec_client/operations/psa_import_key.md
  src/parsec_client/operations/psa_key_attributes.md
  src/parsec_client/operations/psa_sign_hash.md
  src/parsec_client/operations/psa_verify_hash.md
  src/parsec_client/operations/share_trust_bundle.md
  src/parsec_client/status_codes.md
  src/parsec_client/wire_protocol.md
  src/parsec_client/writing_library.md
  src/parsec_service/README.md
  src/parsec_service/adding_provider.md
  src/parsec_service/authenticators.md
  src/parsec_service/build_run.md
  src/parsec_service/configuration.md
  src/parsec_service/converters.md
  src/parsec_service/install_parsec_linux.md
  src/parsec_service/interfaces_and_dataflow.md
  src/parsec_service/key_id_managers.md
  src/parsec_service/listeners.md
  src/parsec_service/providers.md
  src/parsec_service/source_code_structure.md
  src/parsec_service/system_architecture.md
  src/parsec_service/test.md
  src/parsec_users.md
  src/threat_model/threat_model.md
Labels: invalid

#27 Rename key ID to key info
  src/SUMMARY.md
  src/parsec_client/status_codes.md
  src/parsec_service/README.md
  src/parsec_service/adding_provider.md
  src/parsec_service/interfaces_and_dataflow.md
  src/parsec_service/key_id_managers.md
  src/parsec_service/key_info_managers.md
  src/parsec_service/source_code_structure.md
  src/parsec_service/test.md
  src/threat_model/threat_model.md
Labels: invalid
