Repository parallaxsecond/parsec-book, pull requests merged in 2020-07, with the labels that each got.

#41 Add recommendations for secure deployment
  src/SUMMARY.md
  src/parsec_service/build_run.md
  src/parsec_service/install_parsec_linux.md
  src/parsec_service/listeners.md
  src/threat_model/secure_deployment.md
  src/threat_model/threat_model.md
Labels: security

#44 Adjusted asymmetric encrypt and derypt opcodes
  src/parsec_client/operations/psa_asymmetric_decrypt.md
  src/parsec_client/operations/psa_asymmetric_encrypt.md
Labels: documentation

#47 Add a notion of priority in ListProviders
  src/parsec_client/operations/list_providers.md
  src/parsec_service/test.md
Labels: documentation

#50 Update the installation guide
  src/parsec_service/install_parsec_linux.md
Labels: bug, documentation

#51 Directly install from crates.io
  src/parsec_service/install_parsec_linux.md
Labels: enhancement
