Repository parallaxsecond/parsec-book, pull requests merged in 2020-06, with the labels that each got.

#34 Add info about building TPM/PKCS11 providers
  src/parsec_client/operations/psa_algorithm.md
  src/parsec_service/build_run.md
  src/parsec_service/test.md
Labels: documentation

#36 Update the threat model after review
  src/threat_model/diagrams/dataflow_diagram.png
  src/threat_model/diagrams/dataflow_diagram.xml
  src/threat_model/threat_model.md
Labels: documentation

#37 Add Rust Client Threat Model
  src/SUMMARY.md
  src/parsec_service/build_run.md
  src/threat_model/diagrams/rust_client_diagram.png
  src/threat_model/diagrams/rust_client_diagram.xml
  src/threat_model/rust_client_threat_model.md
Labels: documentation, enhancement

#38 Add tickets for mitigations
  src/threat_model/threat_model.md
Labels: security

#39 Add consequences of unmitigations
  src/threat_model/threat_model.md
Labels: documentation

#40 Add details to (un)mitigations
  src/threat_model/rust_client_threat_model.md
Labels: enhancement

#43 Add clients API coverage page
  src/SUMMARY.md
  src/clients_api_coverage.md
  src/parsec_client/operations/psa_algorithm.md
  src/parsec_client/operations/psa_key_attributes.md
  src/service_api_coverage.md
Labels: documentation, enhancement
