Repository parallaxsecond/parsec-book, pull requests merged in 2020-03, with the labels that each got.

#16 Add some information about install TSS
  src/parsec_service/providers.md
Labels: enhancement

#17 Create PSA crypto coverage page
  src/SUMMARY.md
  src/api_coverage.md
  src/parsec_client/operations/psa_asymmetric_sign.md
  src/parsec_client/operations/psa_asymmetric_verify.md
  src/parsec_client/operations/psa_create_key.md
Labels: documentation

#20 Fix dead links
  src/api_coverage.md
  src/parsec_client/operations/psa_asymmetric_sign.md
  src/parsec_client/operations/psa_asymmetric_verify.md
  src/parsec_client/operations/psa_create_key.md
  src/parsec_client/operations/psa_destroy_key.md
  src/parsec_client/operations/psa_export_public_key.md
  src/parsec_client/operations/psa_import_key.md
Labels: bug

#19 Add Parsec Threat Model
  src/SUMMARY.md
  src/threat_model/diagrams/dataflow_diagram.png
  src/threat_model/diagrams/dataflow_diagram.xml
  src/threat_model/threat_model.md
Labels: documentation

#21 Update operations and response codes with PSA 1.0
  src/SUMMARY.md
  src/parsec_client/operations/README.md
  src/parsec_client/operations/key_attributes.md
  src/parsec_client/operations/psa_algorithm.md
  src/parsec_client/operations/psa_create_key.md
  src/parsec_client/operations/psa_export_public_key.md
  src/parsec_client/operations/psa_generate_key.md
  src/parsec_client/operations/psa_key_attributes.md
  src/parsec_client/status_codes.md
Labels: documentation
