Repository parallaxsecond/parsec-book, pull requests merged in 2020-02, with the labels that each got.

#2 Update dev guides; Add self-publishing workflow
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .gitignore
  src/dev_guides/README.md
  src/dev_guides/adding_provider.md
  src/dev_guides/build.md
  src/dev_guides/test.md
  src/parsec/operations/list_opcodes.md
  src/parsec/operations/list_providers.md
Labels: documentation, enhancement

#5 Improve operations documentation
  src/parsec/operations/README.md
  src/parsec/operations/add_client.md
  src/parsec/operations/key_attributes.md
  src/parsec/operations/list_opcodes.md
  src/parsec/operations/list_providers.md
  src/parsec/operations/ping.md
  src/parsec/operations/prove_client.md
  src/parsec/operations/psa_asymmetric_sign.md
  src/parsec/operations/psa_asymmetric_verify.md
  src/parsec/operations/psa_create_key.md
  src/parsec/operations/psa_destroy_key.md
  src/parsec/operations/psa_export_public_key.md
  src/parsec/operations/psa_import_key.md
  src/parsec/operations/share_trust_bundle.md
Labels: documentation, enhancement

#6 Update Parsec for developers section
  src/SUMMARY.md
  src/parsec/use_parsec.md
  src/parsec_dev/README.md
  src/parsec_dev/adding_provider.md
  src/parsec_dev/build_run.md
  src/parsec_dev/configuration.md
  src/parsec_dev/install_parsec_linux.md
  src/parsec_dev/test.md
  src/parsec_dev/use_parsec.md
  src/parsec_dev/writing_library.md
  src/user_guides/README.md
Labels: invalid

#8 Update the interfaces and dataflow diagram
  src/parsec_service/diagrams/interfaces_and_dataflow.drawio
  src/parsec_service/diagrams/interfaces_and_dataflow.png
  src/parsec_service/interfaces_and_dataflow.md
Labels: invalid

#9 Add linting to the CI
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  README.md
  book.toml
  ci/check_format.sh
  parsec.png
  src/README.md
  src/SUMMARY.md
  src/overview.md
  src/parsec_client/README.md
  src/parsec_client/api_overview.md
  src/parsec_client/operations/README.md
  src/parsec_client/operations/add_client.md
  src/parsec_client/operations/key_attributes.md
  src/parsec_client/operations/list_opcodes.md
  src/parsec_client/operations/list_providers.md
  src/parsec_client/operations/ping.md
  src/parsec_client/operations/prove_client.md
  src/parsec_client/operations/psa_asymmetric_sign.md
  src/parsec_client/operations/psa_asymmetric_verify.md
  src/parsec_client/operations/psa_create_key.md
  src/parsec_client/operations/psa_destroy_key.md
  src/parsec_client/operations/psa_export_public_key.md
  src/parsec_client/operations/psa_import_key.md
  src/parsec_client/operations/share_trust_bundle.md
  src/parsec_client/status_codes.md
  src/parsec_client/wire_protocol.md
  src/parsec_client/writing_library.md
  src/parsec_service/README.md
  src/parsec_service/adding_provider.md
  src/parsec_service/build_run.md
  src/parsec_service/configuration.md
  src/parsec_service/install_parsec_linux.md
  src/parsec_service/interfaces_and_dataflow.md
  src/parsec_service/providers.md
  src/parsec_service/source_code_structure.md
  src/parsec_service/system_architecture.md
  src/parsec_service/test.md
  src/parsec_users.md
Labels: enhancement

#10 Update Source Code diagram
  src/parsec_service/diagrams/source_code_structure.drawio
  src/parsec_service/diagrams/source_code_structure.png
Labels: invalid

#11 Add link checking and fix links
  .github/workflows/ci.yml
  README.md
  ci/check_format.sh
  src/parsec_client/api_overview.md
  src/parsec_client/diagrams/wire_request.drawio
  src/parsec_client/diagrams/wire_request.png
  src/parsec_client/diagrams/wire_response.drawio
  src/parsec_client/diagrams/wire_response.png
  src/parsec_client/operations/psa_create_key.md
  src/parsec_client/writing_library.md
  src/parsec_service/source_code_structure.md
  src/parsec_service/system_architecture.md
  src/parsec_users.md
Labels: enhancement

#12 Add information about trait implementors
  src/SUMMARY.md
  src/parsec_client/writing_library.md
  src/parsec_service/README.md
  src/parsec_service/authenticators.md
  src/parsec_service/converters.md
  src/parsec_service/interfaces_and_dataflow.md
  src/parsec_service/key_id_managers.md
  src/parsec_service/listeners.md
Labels: enhancement

#14 Update test command
  src/parsec_service/install_parsec_linux.md
Labels: bug

#15 Add precisions about versioning
  src/parsec_client/operations/list_providers.md
  src/parsec_client/operations/ping.md
  src/parsec_client/status_codes.md
  src/parsec_client/wire_protocol.md
Labels: invalid
