Repository parallaxsecond/parsec-book, pull requests merged in 2020-10, with the labels that each got.

#68 Add PR reviewer checklist
  src/SUMMARY.md
  src/contributing/README.md
  src/contributing/pr_checklist.md
Labels: documentation

#67 Update instraction after installation path changes
  src/parsec_service/build_run.md
  src/parsec_service/install_parsec_linux.md
  src/parsec_service/listeners.md
Labels: invalid

#69 Remove disclaimers and notices
  README.md
  src/README.md
  src/parsec_client/api_overview.md
  src/parsec_client/operations/README.md
  src/parsec_client/wire_protocol.md
  src/parsec_service/interfaces_and_dataflow.md
  src/parsec_service/source_code_structure.md
  src/parsec_service/system_architecture.md
Labels: invalid

#70 Add the ListKeys operation
  src/parsec_client/operations/README.md
  src/parsec_client/operations/list_keys.md
  src/parsec_client/operations/service_api_coverage.md
Labels: enhancement

#71 Update Threat Model
  .github/workflows/ci.yml
  src/contributing/adding_new_operation_how_to.md
  src/parsec_security/parsec_threat_model/threat_model.md
Labels: documentation, multitenancy, security

#74 Update the book after security changes
  src/parsec_security/parsec_threat_model/threat_model.md
  src/parsec_security/secure_deployment.md
  src/parsec_service/authenticators.md
  src/parsec_service/build_run.md
  src/parsec_service/diagrams/source_code_structure.drawio
  src/parsec_service/diagrams/source_code_structure.png
  src/parsec_service/install_parsec_linux.md
  src/parsec_service/tests/existing_tests.md
  src/parsec_users.md
Labels: multitenancy, security
